### ISSUE TITLE
convert issue doesn't seem to be solved on windows

### ISSUE THREAD

**Issue by jfoclpf** [dwmkerr/node-imagemagick-cli#46]
This code 
```js
const imagemagickCli = require('imagemagick-cli')

//...
//...

imagemagickCli
  .exec(`convert ${filename} -strip ${filename + '.min'}`)
  .then(({ stdout, stderr }) => {
    if (stderr) {
      callback(Error('Error compressing ' + filename + '. ' + stderr))
    } else {
      // removes original and renames
      fs.unlinkSync(filename)
      fs.renameSync(filename + '.min', filename)
    }
  }).catch(err => {
    callback(Error('Error compressing ' + filename + '. ' + err))
  })
```

return this on windows

```
Error: Error compressing D:\a\autocosts\autocosts\bin\public\favicon.png. Error: Failed to call 'convert D:\a\autocosts\autocosts\bin\public\favicon.png -strip D:\a\autocosts\autocosts\bin\public\favicon.png.min', which was mapped to '"C:\Windows\System32\convert.exe" D:\a\autocosts\autocosts\bin\public\favicon.png -strip D:\a\autocosts\autocosts\bin\public\favicon.png.min'. Error is 'Command failed: "C:\Windows\System32\convert.exe" D:\a\autocosts\autocosts\bin\public\favicon.png -strip D:\a\autocosts\autocosts\bin\public\favicon.png.min
Invalid Parameter - -strip
'.
    at D:\a\autocosts\autocosts\build\compressImages.js:39:17
    at D:\a\autocosts\autocosts\node_modules\async\dist\async.js:2955:19
    at wrapper (D:\a\autocosts\autocosts\node_modules\async\dist\async.js:268:20)
    at iteratorCallback (D:\a\autocosts\autocosts\node_modules\async\dist\async.js:493:17)
    at D:\a\autocosts\autocosts\node_modules\async\dist\async.js:321:20
    at D:\a\autocosts\autocosts\node_modules\async\dist\async.js:2953:17
    at D:\a\autocosts\autocosts\build\compressImages.js:130:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! Test failed.  See above for more details.
Error: Process completed with exit code 1.
```

**Comment by jfoclpf** [comment]
chocolately said it was installed here
```
Software installed to 'C:\Program Files\ImageMagick-7.1.0-Q16-HDRI\'
```
